project_id = "mayoefzlcnqbukodziyt"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.scrape-obituaries]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.update-cron-schedule]
verify_jwt = false
